"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from backend.settings.base import *
from backend.settings.apps import *
from backend.settings.app_vars import *
from backend.settings.logger import *
from backend.settings.database import *
from backend.settings.third_party import *