# Generated by Django 3.2.18 on 2023-02-19 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('doc_title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('doc_body', models.TextField(blank=True, default=None, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
            ],
            options={
                'verbose_name': 'user_document',
                'verbose_name_plural': 'user_documents',
                'db_table': 'user_document',
                'ordering': ['id'],
            },
        ),
    ]
