# Generated by Django 3.2.18 on 2023-02-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collection_collection_creator'),
        ('document', '0002_document_doc_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_status',
            field=models.IntegerField(choices=[(1, 'DRAFTED'), (2, 'PUBLISHED'), (3, 'DELETED'), (4, 'ARCHIVED')], default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='collection.collection'),
        ),
    ]
