# Generated by Django 3.2.18 on 2023-02-19 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('collection_title', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'user_collection',
                'verbose_name_plural': 'user_collection',
                'db_table': 'user_collection',
                'ordering': ['id'],
            },
        ),
    ]
