# Generated by Django 3.2.18 on 2023-02-18 08:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, always_update=True, editable=False, populate_from='first_name', unique=True)),
                ('email', models.EmailField(db_index=True, max_length=200, unique=True)),
                ('customer_code', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('member_code', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('acc_number', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('alternative_mobile', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address_one', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('address_two', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'NONE'), (2, 'MALE'), (3, 'FEMALE'), (4, 'NOT_SET')], default=1)),
                ('telephone', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('nid', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('preferred_payment_method', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('is_customer', models.BooleanField(blank=True, default=False, null=True)),
                ('is_wholesaler', models.BooleanField(blank=True, default=False, null=True)),
                ('is_retailer', models.BooleanField(blank=True, default=False, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this user should be treated as active. Unselect             this instead of deleting accounts.', verbose_name='active')),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['-date_joined'],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
    ]
